data ResultWithIO typevariableforpureexpressions typevariableforioexpressions
	= PureConstructor_1 ....
	| PureConstructor_2 ....
	| IOContrcutor_1 .....
	| IOContructor_2 ...
	| ContructorWithBoth_1 .....
	| ContructorWithBoth_2 .....
	deriving(........)